// src/app/layout.tsx
import Navigation from './components/Navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />    {/* Global Nav goes here */}
        {children}        {/* Page content goes here */}
        <footer style={{ marginTop: "2em", padding: "1.5em", textAlign: "center", fontSize: "14px", color: "#888" }}>
        &copy; {new Date().getFullYear()} SparkBytes. All rights reserved.
      </footer>
      </body>
    </html>
  );
}