// src/app/layout.tsx
// import "antd/dist/reset.css";
import Navigation from './components/Navigation';

// import './global.css';
import 'leaflet/dist/leaflet.css';

// import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}